security:
  jwt:
    token:
      secret-key: ${SECRETKEY}
      expire-length: 7200000

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false

  jackson:
    time-zone: America/Sao_Paulo
  mvc:
    locale: pt_BR
    locale-resolver: fixed


mail:
  host: smtp.gmail.com
  port: 587
  username: ${EMAIL}
  password: ${PASSWORDEMAIL}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
  test-connection: true

springdoc:
  swagger-ui:
    use-root-path: true
  packagesToScan: io.github.karMiguel.capzip.controllers

cors:
  originPatterns:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://localhost:4200"

DOMAIN_URL: ${DOMAIN_URL}

